[[session]]
name = "agencieshq"
path = "~/work/agencieshq/master"

[[session]]
name = "has_data_imports"
path = "~/work/gems/has_data_imports/master"

[[session]]
name = "has_helpers"
path = "~/work/gems/has_helpers/master"

[[session]]
name = "hq-graphql"
path = "~/work/gems/hq-graphql/master"

[[session]]
name = "readygop"
path = "~/work/readygop/main"

[[session]]
name = "readygop-ui"
path = "~/work/readygop-ui/main"
