# true color
set-option -sa terminal-overrides ",xterm*:Tc"

# status line
set -g status-position top

# mouse support
set -g mouse on

# prefix key
set-option -g prefix C-A
unbind-key C-b
bind-key C-A send-prefix

bind-key j run-shell "tmux display-popup -E 'sesh connect \"\$(sesh list -i | gum filter --limit 1 --placeholder \"Choose a session\" --height 50 --prompt \"⚡\")\"'"

# reload
bind r source-file ~/.config/tmux/tmux.conf

# index (windows and panes)
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on

# vi mode
set-window-option -g mode-keys vi

# catpuccin theme
set -g @catppuccin_flavour 'macchiato'
set -g @catppuccin_status_modules_right "none"
set -g @catppuccin_window_default_text "#S"
set -g @catppuccin_window_current_text "#S"


# tmux plugins
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.tmux/plugins"
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'

run '~/.tmux/plugins/tpm/tpm'

bind-key -r f run-shell "tmux neww ~/.config/bin/tmux-sessionizer"
