# true color
set-option -sa terminal-overrides ",xterm*:Tc"

# mouse support
set -g mouse on

# prefix key
set-option -g prefix C-Space
unbind-key C-b
bind-key C-Space send-prefix

# index (windows and panes)
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on

# vi mode
set-window-option -g mode-keys vi

# catpuccin theme
set -g @catppuccin_flavour 'macchiato'

# tmux plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'

run '~/.tmux/plugins/tpm/tpm'
