include nightfox.conf

# Reload config
map ctrl+cmd+,  load_config_file

# Fonts
adjust_line_height  175%
bold_font           Hack Bold Nerd Font
bold_italic_font    Hack Bold Italic Nerd Font
font_family         Hack Regular Nerd Font
font_size           15.0
italic_font         Hack Italic Nerd Font

# Cursor
cursor                none
cursor_blink_interval 0
cursor_shape          block

# Mouse
mouse_hide_wait 3.0
copy_on_select  true

# Terminal bell
enable_audio_bell false

# Window layout
active_border_color     #00ff00
confirm_os_window_close 0
hide_window_decorations no
remember_window_size    no
window_border_width     2
window_padding_width    10
