# Theme - Catppuccin
# See more: https://github.com/catppuccin/kitty
include ~/shared/kitty/themes/mocha.conf

# Fonts - Hack Nerd Font with styles
font_family         Hack Regular Nerd Font
font_size           15.0
bold_font           Hack Bold Nerd Font
italic_font         Hack Italic Nerd Font
bold_italic_font    Hack Bold Italic Nerd Font
adjust_line_height  150%

# Cursor
cursor_shape          block
cursor_blink_interval 0

# Terminal Bell
enable_audio_bell false

# Window Appearance
window_padding_width    10
window_border_width     2
active_border_color     #00ff00
hide_window_decorations yes
remember_window_size    no
confirm_os_window_close 0

